/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miguel
 */
public class CalculatorGUI extends javax.swing.JFrame {
    
    
    double firstname, secondname, result;
    String operations;

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisplay = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        buton8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonInvert = new javax.swing.JButton();
        buttonDecimal = new javax.swing.JButton();
        buttonPow = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonLog = new javax.swing.JButton();
        buttonLn = new javax.swing.JButton();
        buttonSqrt = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        buttonCot = new javax.swing.JButton();
        buttonLeftBracket = new javax.swing.JButton();
        buttonRightBracket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        buton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buton8.setText("8");
        buton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton8ActionPerformed(evt);
            }
        });

        button9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonSubtract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSubtract.setText("-");
        buttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtractActionPerformed(evt);
            }
        });

        buttonDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonMultiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonMultiply.setText("*");
        buttonMultiply.setToolTipText("");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonInvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonInvert.setText("+/-");
        buttonInvert.setToolTipText("");
        buttonInvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvertActionPerformed(evt);
            }
        });

        buttonDecimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonDecimal.setText(".");
        buttonDecimal.setToolTipText("");
        buttonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecimalActionPerformed(evt);
            }
        });

        buttonPow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonPow.setText("^");
        buttonPow.setToolTipText("");
        buttonPow.setActionCommand("sin");
        buttonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowActionPerformed(evt);
            }
        });

        buttonSin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSin.setText("sin");
        buttonSin.setToolTipText("");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonCos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonCos.setText("cos");
        buttonCos.setToolTipText("");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        buttonTan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonTan.setText("tan");
        buttonTan.setToolTipText("");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });

        buttonLog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonLog.setText("log");
        buttonLog.setToolTipText("");
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });

        buttonLn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonLn.setText("ln");
        buttonLn.setToolTipText("");
        buttonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLnActionPerformed(evt);
            }
        });

        buttonSqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonSqrt.setText("sqrt");
        buttonSqrt.setToolTipText("");
        buttonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSqrtActionPerformed(evt);
            }
        });

        buttonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonClear.setText("clear");
        buttonClear.setToolTipText("");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonEquals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.setToolTipText("");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        buttonCot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonCot.setText("cot");
        buttonCot.setToolTipText("");
        buttonCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCotActionPerformed(evt);
            }
        });

        buttonLeftBracket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonLeftBracket.setText("(");
        buttonLeftBracket.setToolTipText("");
        buttonLeftBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLeftBracketActionPerformed(evt);
            }
        });

        buttonRightBracket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonRightBracket.setText(")");
        buttonRightBracket.setToolTipText("");
        buttonRightBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRightBracketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisplay)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonCot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonLeftBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonRightBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonLn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonInvert, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonSubtract, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonDecimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonTan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSqrt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonEquals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInvert, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonLeftBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRightBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + button1.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button2.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button3.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button4.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button5.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button6.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button7.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button7ActionPerformed

    private void buton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton8ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + buton8.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_buton8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button9.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + button0.getText();
        jtxtDisplay.setText(displayText);
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + " " + buttonAdd.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubtractActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() +  " " + buttonSubtract.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonSubtractActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() +  " " + buttonDivide.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() +  " " + buttonMultiply.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonInvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvertActionPerformed
        // TODO add your handling code here:   
         String[] tokens = jtxtDisplay.getText().split(" ");
         int lastIndex = tokens.length-1;
         
         if(ExpressionCalculator.isOperator(tokens[lastIndex])) return;
         
         if(tokens[lastIndex].startsWith("-")){
             tokens[lastIndex] = tokens[lastIndex].replace("-", "");
         }else{
             tokens[lastIndex] = "-"+tokens[lastIndex];
         }
         
         String newDisplayText = "";
         for(String str : tokens){
             newDisplayText += (str + " ");
         }
         
        jtxtDisplay.setText(newDisplayText);
    }//GEN-LAST:event_buttonInvertActionPerformed

    private void buttonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecimalActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText().stripTrailing();
        jtxtDisplay.setText(displayText + ".");
    }//GEN-LAST:event_buttonDecimalActionPerformed

    private void buttonPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + buttonPow.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonPowActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + buttonSin.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + buttonCos.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + buttonTan.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        String displayText = jtxtDisplay.getText() + buttonLog.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonLogActionPerformed

    private void buttonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLnActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
         String displayText = jtxtDisplay.getText() + buttonLn.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonLnActionPerformed

    private void buttonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSqrtActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        
         String displayText = jtxtDisplay.getText() + buttonSqrt.getText();
        jtxtDisplay.setText(displayText + " ( ");
    }//GEN-LAST:event_buttonSqrtActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:

        jtxtDisplay.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
        // TODO add your handling code here:
        
        try {
            String calcResult = " = " + ExpressionCalculator.evaluate(jtxtDisplay.getText());
            String displayText = jtxtDisplay.getText() + calcResult;
            jtxtDisplay.setText(displayText + " ");
        }catch (Exception e){
           jtxtDisplay.setText("ERROR: Incorrect Input");
        }
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
        
         String displayText = jtxtDisplay.getText() + buttonCot.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void buttonCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCotActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
           
        
         String displayText = jtxtDisplay.getText() + buttonCot.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonCotActionPerformed

    private void buttonLeftBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLeftBracketActionPerformed
        // TODO add your handling code here:
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }        
        
          String displayText = jtxtDisplay.getText() + " " + buttonLeftBracket.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonLeftBracketActionPerformed

    private void buttonRightBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRightBracketActionPerformed
        // TODO add your handling code here:
            
        if(jtxtDisplay.getText().contains("=") || jtxtDisplay.getText().contains("ERROR:")){
            jtxtDisplay.setText("");
        }
           
          String displayText = jtxtDisplay.getText() + " " + buttonRightBracket.getText();
        jtxtDisplay.setText(displayText + " ");
    }//GEN-LAST:event_buttonRightBracketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton8;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonCot;
    private javax.swing.JButton buttonDecimal;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonInvert;
    private javax.swing.JButton buttonLeftBracket;
    private javax.swing.JButton buttonLn;
    private javax.swing.JButton buttonLog;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonPow;
    private javax.swing.JButton buttonRightBracket;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonSqrt;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JButton buttonTan;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
